// This adapter is the single frontend boundary to Convex's generated API.
// Function names and argument/result types remain generated by Convex, never duplicated here.
export { api } from "../../../../convex/_generated/api";
