export const ciTooling = [
  {
    name: "VPS_HOST",
    group: "CI / deployment tooling",
    scope: "runtime",
    local: "game.rahmanef.com",
    production: "game.rahmanef.com",
    secret: false,
    description:
      "Hostname routed by the VPS Traefik labels; may be overridden for a staging-origin validation.",
    source: "Canonical production domain / VPS deployment override",
  },
  {
    name: "VPS_GITHUB_REPOSITORY",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "rahmanef63/play-together",
    production: "rahmanef63/play-together",
    secret: false,
    description: "Public GitHub repository queried by the CI-gated VPS deploy watcher.",
    source: "Project repository identity",
  },
  {
    name: "VPS_DEPLOY_STATE_FILE",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-vps-deployed-sha-state-path>",
    production: "<owner-only-vps-deployed-sha-state-path>",
    secret: false,
    description: "Optional state path storing the last successfully deployed production Git SHA.",
    source: "VPS operator configuration; defaults under ~/.local/state/play-together",
  },
  {
    name: "VPS_ENV_FILE",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-path-to-private-vps-env-file>",
    production: "<private-vps-env-file-path>",
    secret: false,
    description: "Optional path to the private env file consumed by pnpm vps:deploy.",
    source: "VPS operator configuration; defaults to .env.vps.production in the checkout",
  },
  {
    name: "VERCEL_TOKEN",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-access-token>",
    secret: true,
    description: "CLI/CI deployment token.",
    source: "Vercel account settings → Tokens",
  },
  {
    name: "VERCEL_ORG_ID",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-team-or-user-id>",
    secret: false,
    description: "Vercel project owner/team ID.",
    source: "Vercel project link metadata (.vercel/project.json)",
  },
  {
    name: "VERCEL_PROJECT_ID",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-project-id>",
    secret: false,
    description: "Vercel project ID.",
    source: "Vercel project settings or .vercel/project.json",
  },
  {
    name: "E2E_BASE_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://localhost:4173",
    production: "https://game.rahmanef.com",
    secret: false,
    description: "Playwright target application URL.",
    source: "Project configuration / platform integration",
  },
  {
    name: "E2E_REALTIME_HEALTH_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://127.0.0.1:8787/healthz",
    production: "https://game.rahmanef.com/api/realtime",
    secret: false,
    description: "Playwright/release realtime readiness endpoint.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CHROME_PATH",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "/usr/bin/google-chrome",
    production: "<chrome-executable-path>",
    secret: false,
    description: "Optional Playwright Chrome executable override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "PREVIEW_GAME_ID",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-game-id>",
    production: "<optional-game-id>",
    secret: false,
    description: "Limits gameplay preview capture to one game.",
    source: "Project configuration / platform integration",
  },
  {
    name: "REDIS_TEST_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-redis-test-url>",
    production: "<optional-redis-test-url>",
    secret: true,
    description: "Enables the Redis integration test when explicitly supplied.",
    source: "Project configuration / platform integration",
  },
];
