export const ciTooling = [
  {
    name: "VPS_HOST",
    group: "CI / deployment tooling",
    scope: "runtime",
    local: "game.rahmanef.com",
    production: "game.rahmanef.com",
    secret: false,
    description:
      "Hostname routed by the VPS Traefik labels; may be overridden for a staging-origin validation.",
    source: "Canonical production domain / VPS deployment override",
  },
  {
    name: "VPS_GITHUB_REPOSITORY",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "rahmanef63/play-together",
    production: "rahmanef63/play-together",
    secret: false,
    description: "Public GitHub repository queried by the CI-gated VPS deploy watcher.",
    source: "Project repository identity",
  },
  {
    name: "PLAY_TOGETHER_UPSTREAM",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "https://github.com/rahmanef63/play-together.git",
    production: "https://github.com/rahmanef63/play-together.git",
    secret: false,
    description: "Canonical repository used by pnpm repo:update for safe clone/fork synchronization.",
    source: "Project repository identity",
  },
  {
    name: "PLAY_TOGETHER_UPSTREAM_BRANCH",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "main",
    production: "main",
    secret: false,
    description: "Canonical branch used by pnpm repo:update for safe clone/fork synchronization.",
    source: "Project repository identity",
  },
  {
    name: "VPS_DEPLOY_STATE_FILE",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-vps-deployed-sha-state-path>",
    production: "<owner-only-vps-deployed-sha-state-path>",
    secret: false,
    description:
      "Optional non-secret state path storing the last fully published production Git SHA for health/readiness gating.",
    source: "VPS operator configuration; defaults under ~/.local/state/play-together",
  },
  {
    name: "VPS_ENV_FILE",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-path-to-private-vps-env-file>",
    production: "<private-vps-env-file-path>",
    secret: false,
    description: "Optional path to the private env file consumed by pnpm vps:deploy.",
    source: "VPS operator configuration; defaults to .env.vps.production in the checkout",
  },

  {
    name: "E2E_BASE_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://localhost:4173",
    production: "https://game.rahmanef.com",
    secret: false,
    description: "Playwright target application URL.",
    source: "Project configuration / platform integration",
  },
  {
    name: "E2E_REALTIME_HEALTH_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://127.0.0.1:8787/healthz",
    production: "https://game.rahmanef.com/api/realtime",
    secret: false,
    description: "Playwright/release realtime readiness endpoint.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CHROME_PATH",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "/usr/bin/google-chrome",
    production: "<chrome-executable-path>",
    secret: false,
    description: "Optional Playwright Chrome executable override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "PREVIEW_GAME_ID",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-game-id>",
    production: "<optional-game-id>",
    secret: false,
    description: "Limits gameplay preview capture to one game.",
    source: "Project configuration / platform integration",
  },
  {
    name: "REDIS_TEST_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-redis-test-url>",
    production: "<optional-redis-test-url>",
    secret: true,
    description: "Enables the Redis integration test when explicitly supplied.",
    source: "Project configuration / platform integration",
  },
];
