export const ciTooling = [
  {
    name: "VERCEL_TOKEN",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-access-token>",
    secret: true,
    description: "CLI/CI deployment token.",
    source: "Vercel account settings → Tokens",
  },
  {
    name: "VERCEL_ORG_ID",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-team-or-user-id>",
    secret: false,
    description: "Vercel project owner/team ID.",
    source: "Vercel project link metadata (.vercel/project.json)",
  },
  {
    name: "VERCEL_PROJECT_ID",
    group: "CI / deployment tooling",
    scope: "ci",
    production: "<vercel-project-id>",
    secret: false,
    description: "Vercel project ID.",
    source: "Vercel project settings or .vercel/project.json",
  },
  {
    name: "E2E_BASE_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://localhost:4173",
    production: "https://game.rahmanef.com",
    secret: false,
    description: "Playwright target application URL.",
    source: "Project configuration / platform integration",
  },
  {
    name: "E2E_REALTIME_HEALTH_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "http://127.0.0.1:8787/healthz",
    production: "https://game.rahmanef.com/api/realtime",
    secret: false,
    description: "Playwright/release realtime readiness endpoint.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CHROME_PATH",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "/usr/bin/google-chrome",
    production: "<chrome-executable-path>",
    secret: false,
    description: "Optional Playwright Chrome executable override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "PREVIEW_GAME_ID",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-game-id>",
    production: "<optional-game-id>",
    secret: false,
    description: "Limits gameplay preview capture to one game.",
    source: "Project configuration / platform integration",
  },
  {
    name: "REDIS_TEST_URL",
    group: "CI / deployment tooling",
    scope: "tooling",
    local: "<optional-redis-test-url>",
    production: "<optional-redis-test-url>",
    secret: true,
    description: "Enables the Redis integration test when explicitly supplied.",
    source: "Project configuration / platform integration",
  },
];
