export const internalRuntime = [
  {
    name: "HOST",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "127.0.0.1",
    production: "0.0.0.0",
    secret: false,
    description: "HTTP/realtime bind host override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "PORT",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "<service-port>",
    production: "<platform-assigned-port>",
    secret: false,
    description: "HTTP/realtime bind port override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "WEB_ROOT",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "<optional-web-dist-path>",
    production: "<optional-web-dist-path>",
    secret: false,
    description: "Static web root override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "GAME_CDN_ROOT",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "releases/game-cdn",
    production: "<immutable-game-cdn-root>",
    secret: false,
    description: "Immutable game CDN filesystem root.",
    source: "Project configuration / platform integration",
  },
  {
    name: "GAME_WORKER_PATH",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "apps/realtime/dist/game-worker.js",
    production: "<built-game-worker-path>",
    secret: false,
    description: "Realtime worker bundle override.",
    source: "Project configuration / platform integration",
  },
  {
    name: "MODULE_CACHE_DIR",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: ".cache/game-modules",
    production: "/tmp/play-together-game-modules",
    secret: false,
    description: "Verified game module cache directory.",
    source: "Project configuration / platform integration",
  },
  {
    name: "REALTIME_CONNECT_PATH",
    group: "Internal runtime overrides",
    scope: "runtime",
    local: "/v1/connect",
    production: "/api/realtime",
    secret: false,
    description: "Realtime WebSocket connect path override.",
    source: "Project realtime runtime configuration",
  },
];
