export const localPorts = [
  {
    name: "COMPOSE_PROJECT_NAME",
    group: "Local ports & Compose",
    scope: "local",
    local: "play-together",
    production: "play-together",
    secret: false,
    description: "Project-owned Compose namespace.",
    source: "Project configuration / platform integration",
  },
  {
    name: "BIND_ADDRESS",
    group: "Local ports & Compose",
    scope: "local",
    local: "127.0.0.1",
    secret: false,
    description: "Host interface for local published ports.",
    source: "Project configuration / platform integration",
  },
  {
    name: "WEB_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "4173",
    secret: false,
    description: "Local web port.",
    source: "Project configuration / platform integration",
  },
  {
    name: "REALTIME_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "8787",
    secret: false,
    description: "Local realtime port.",
    source: "Project configuration / platform integration",
  },
  {
    name: "GAME_CDN_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "8081",
    secret: false,
    description: "Local immutable game CDN port.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CONVEX_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "43210",
    secret: false,
    description: "Local self-hosted Convex API port.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CONVEX_SITE_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "43211",
    secret: false,
    description: "Local self-hosted Convex site port.",
    source: "Project configuration / platform integration",
  },
  {
    name: "CONVEX_DASHBOARD_PORT",
    group: "Local ports & Compose",
    scope: "local",
    local: "46791",
    secret: false,
    description: "Local Convex dashboard port.",
    source: "Project configuration / platform integration",
  },
];
