export const managedRuntime = [
  {
    name: "REDIS_URL",
    group: "Managed production runtime",
    scope: "production",
    production: "<vercel-redis-connection-url>",
    secret: true,
    description: "Cross-function room coordination and release-control Redis connection.",
    source: "Vercel project → Storage/Marketplace Redis integration",
  },
  {
    name: "BLOB_READ_WRITE_TOKEN",
    group: "Managed production runtime",
    scope: "production",
    production: "<vercel-private-blob-token>",
    secret: true,
    description: "Private template package Blob credential.",
    source: "Vercel project → Storage → Blob",
  },
  {
    name: "REQUIRE_DISTRIBUTED_COORDINATION",
    group: "Managed production runtime",
    scope: "both",
    local: "false",
    production: "true",
    secret: false,
    description: "Fails production realtime startup when distributed coordination is unavailable.",
    source: "Project configuration / platform integration",
  },
  {
    name: "RELEASE_CONTROL_REQUIRED",
    group: "Managed production runtime",
    scope: "production",
    production: "true",
    secret: false,
    description: "Requires release-control mirror reconciliation during managed publication.",
    source: "Project configuration / platform integration",
  },
  {
    name: "ALLOW_MISSING_ORIGIN",
    group: "Managed production runtime",
    scope: "runtime",
    local: "false",
    production: "false",
    secret: false,
    description:
      "Realtime compatibility override; keep false outside explicit non-browser testing.",
    source: "Project configuration / platform integration",
  },
  {
    name: "ROOM_IDLE_TIMEOUT_MS",
    group: "Managed production runtime",
    scope: "both",
    local: "30000",
    production: "30000",
    secret: false,
    description: "Room worker idle timeout.",
    source: "Project configuration / platform integration",
  },
  {
    name: "MAX_PAYLOAD_BYTES",
    group: "Managed production runtime",
    scope: "both",
    local: "65536",
    production: "65536",
    secret: false,
    description: "Maximum realtime payload size.",
    source: "Project configuration / platform integration",
  },
  {
    name: "VERCEL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Vercel runtime marker used to enforce managed coordination behavior.",
    source: "Automatically injected by Vercel",
  },
  {
    name: "VERCEL_URL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Current Vercel deployment hostname used for exact origin admission.",
    source: "Automatically injected by Vercel",
  },
  {
    name: "VERCEL_PROJECT_PRODUCTION_URL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Canonical Vercel production hostname used for origin admission.",
    source: "Automatically injected by Vercel",
  },
];
