export const managedRuntime = [
  {
    name: "TICKET_VERIFIER_CONVEX_URL",
    group: "Managed production runtime",
    scope: "runtime",
    local: "<optional-convex-ticket-verifier-url>",
    production: "<production-convex-deployment-url>",
    secret: false,
    description:
      "Server-side Convex deployment used by VPS gateways to verify signed realtime and template tickets without copying their HMAC secrets onto the VPS.",
    source: "Primary Convex Cloud deployment URL",
  },
  {
    name: "TICKET_VERIFIER_TIMEOUT_MS",
    group: "Managed production runtime",
    scope: "runtime",
    local: "5000",
    production: "5000",
    secret: false,
    description:
      "Fail-closed timeout for one-time Convex ticket verification during realtime/template authorization.",
    source: "Project runtime policy",
  },
  {
    name: "APP_REVISION",
    group: "Managed production runtime",
    scope: "runtime",
    local: "unknown",
    production: "<injected-deployment-git-sha>",
    secret: false,
    description: "Exact Git revision reported by the VPS production health endpoint.",
    source: "Injected by scripts/deploy-vps.mjs",
  },
  {
    name: "REDIS_URL",
    group: "Managed production runtime",
    scope: "production",
    production: "<managed-redis-connection-url>",
    secret: true,
    description: "Cross-function room coordination and release-control Redis connection.",
    source:
      "Existing managed Redis integration → private VPS env and CI release-control verification",
  },
  {
    name: "BLOB_READ_WRITE_TOKEN",
    group: "Managed production runtime",
    scope: "production",
    production: "<vercel-private-blob-token>",
    secret: true,
    description:
      "Private template package Blob credential; retained as an external storage dependency during the VPS compute cutover.",
    source: "Existing Vercel Blob store → private VPS env",
  },
  {
    name: "REQUIRE_DISTRIBUTED_COORDINATION",
    group: "Managed production runtime",
    scope: "both",
    local: "false",
    production: "true",
    secret: false,
    description:
      "Fails production realtime startup when Redis coordination/release-control is unavailable.",
    source: "Project configuration / platform integration",
  },
  {
    name: "RELEASE_CONTROL_REQUIRED",
    group: "Managed production runtime",
    scope: "production",
    production: "true",
    secret: false,
    description: "Requires release-control mirror reconciliation during managed publication.",
    source: "Project configuration / platform integration",
  },
  {
    name: "ALLOW_MISSING_ORIGIN",
    group: "Managed production runtime",
    scope: "runtime",
    local: "false",
    production: "false",
    secret: false,
    description:
      "Realtime compatibility override; keep false outside explicit non-browser testing.",
    source: "Project configuration / platform integration",
  },
  {
    name: "ROOM_IDLE_TIMEOUT_MS",
    group: "Managed production runtime",
    scope: "both",
    local: "30000",
    production: "30000",
    secret: false,
    description: "Room worker idle timeout.",
    source: "Project configuration / platform integration",
  },
  {
    name: "MAX_PAYLOAD_BYTES",
    group: "Managed production runtime",
    scope: "both",
    local: "65536",
    production: "65536",
    secret: false,
    description: "Maximum realtime payload size.",
    source: "Project configuration / platform integration",
  },
  {
    name: "VERCEL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Vercel runtime marker used to enforce managed coordination behavior.",
    source: "Automatically injected by Vercel",
  },
  {
    name: "VERCEL_URL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Current Vercel deployment hostname used for exact origin admission.",
    source: "Automatically injected by Vercel",
  },
  {
    name: "VERCEL_PROJECT_PRODUCTION_URL",
    group: "Managed production runtime",
    scope: "platform",
    production: "<provided-by-vercel>",
    secret: false,
    description: "Canonical Vercel production hostname used for origin admission.",
    source: "Automatically injected by Vercel",
  },
];
