export const transactionalEmail = [
  {
    name: "RESEND_API_KEY",
    group: "Transactional email",
    scope: "production",
    production: "<resend-server-api-key>",
    secret: true,
    description: "Server-only Resend API key.",
    source: "Resend dashboard → API Keys",
  },
  {
    name: "EMAIL_FROM_ADDRESS",
    group: "Transactional email",
    scope: "both",
    local: "official@rahmanef.com",
    production: "official@rahmanef.com",
    secret: false,
    description: "Verified transactional sender address.",
    source: "Resend dashboard → Domains after DNS verification",
  },
  {
    name: "EMAIL_PROJECT_NAME",
    group: "Transactional email",
    scope: "both",
    local: "Play Together",
    production: "Play Together",
    secret: false,
    description: "Brand name rendered in transactional email.",
    source: "Project configuration / platform integration",
  },
  {
    name: "EMAIL_PROJECT_TAG",
    group: "Transactional email",
    scope: "both",
    local: "play-together-local",
    production: "play-together",
    secret: false,
    description: "Stable project tag sent to the email provider.",
    source: "Project configuration / platform integration",
  },
  {
    name: "EMAIL_REPLY_TO",
    group: "Transactional email",
    scope: "both",
    local: "<optional-reply-to-address>",
    production: "<optional-reply-to-address>",
    secret: false,
    description: "Optional reply-to mailbox.",
    source: "Project configuration / platform integration",
  },
  {
    name: "EMAIL_SITE_URL",
    group: "Transactional email",
    scope: "both",
    local: "http://localhost:4173",
    production: "https://game.rahmanef.com",
    secret: false,
    description: "Canonical site link used in email header/footer.",
    source: "Project configuration / platform integration",
  },
];
