export function starterServer(id) {
  return `import type { CreateServerGame, ServerGame, ServerGameContext, ServerPlayer } from "@play-together/game-sdk";\n\ninterface PlayerState { id: string; score: number; lastAction: string | null }\ninterface State { kind: "${id}"; ticks: number; players: PlayerState[] }\n\nclass StarterGame implements ServerGame {\n  readonly #state: State = { kind: "${id}", ticks: 0, players: [] };\n  readonly #lastSeq = new Map<string, number>();\n  constructor(_context: ServerGameContext) {}\n  onJoin(player: ServerPlayer) {\n    if (!this.#state.players.some((item) => item.id === player.id)) this.#state.players.push({ id: player.id, score: 0, lastAction: null });\n  }\n  onLeave(playerId: string) {\n    this.#state.players = this.#state.players.filter((item) => item.id !== playerId);\n    this.#lastSeq.delete(playerId);\n  }\n  onInput(playerId: string, payload: unknown, sequence: number) {\n    const previous = this.#lastSeq.get(playerId) ?? -1;\n    if (sequence <= previous || typeof payload !== "object" || payload === null) return;\n    const action = (payload as { action?: unknown }).action;\n    if (typeof action !== "string") return;\n    const player = this.#state.players.find((item) => item.id === playerId);\n    if (!player) return;\n    this.#lastSeq.set(playerId, sequence);\n    player.lastAction = action;\n    player.score += 1;\n  }\n  tick(_nowMs: number, _deltaMs: number) { this.#state.ticks += 1; }\n  snapshot() { return structuredClone(this.#state); }\n}\n\nexport const createServerGame: CreateServerGame = (context) => new StarterGame(context);\n`;
}

export function starterDisplay(id, title) {
  return `import type { DisplayGameModule } from "@play-together/game-sdk";\n\ninterface State { kind: "${id}"; ticks: number; players: Array<{ id: string; score: number; lastAction: string | null }> }\nconst isState = (value: unknown): value is State => typeof value === "object" && value !== null && (value as { kind?: unknown }).kind === "${id}";\n\nexport const mountDisplay: DisplayGameModule["mountDisplay"] = (root, context) => {\n  root.replaceChildren();\n  const surface = document.createElement("section");\n  surface.style.cssText = "width:100%;height:100%;display:grid;place-content:center;gap:18px;padding:clamp(20px,5vw,56px);background:#11131a;color:#fff;font-family:system-ui;text-align:center";\n  const heading = document.createElement("h1");\n  heading.textContent = ${JSON.stringify(title)};\n  heading.style.cssText = "margin:0;font-size:clamp(34px,8vw,88px);letter-spacing:-.05em";\n  const status = document.createElement("p");\n  status.style.cssText = "margin:0;color:#aab2c0";\n  surface.append(heading, status);\n  root.append(surface);\n  const unsubscribe = context.subscribe((message) => {\n    if (!isState(message.state)) return;\n    const score = message.state.players.map((player, index) => \`P\${index + 1}: \${player.score}\`).join(" · ");\n    status.textContent = score || "Waiting for players";\n  });\n  return () => { unsubscribe(); root.replaceChildren(); };\n};\n`;
}

export function starterTest(id) {
  return `import { describe, expect, it } from "vitest";\nimport { createServerGame } from "./server.js";\n\ndescribe(${JSON.stringify(id)}, () => {\n  it("accepts a joined player input through the authoritative server", async () => {\n    const game = await createServerGame({ roomId: "room", gameId: ${JSON.stringify(id)}, gameVersion: "0.1.0", seed: 1 });\n    await game.onJoin({ id: "p1", connectedAt: 0 });\n    await game.onInput("p1", { action: "a" }, 1);\n    const state = game.snapshot() as { players: Array<{ score: number }> };\n    expect(state.players[0]?.score).toBe(1);\n  });\n});\n`;
}
